// Code generated by http://github.com/gojuno/minimock (v3.4.5). DO NOT EDIT.

package mocks

import (
	"context"
	"sync"
	mm_atomic "sync/atomic"
	mm_time "time"

	mm_service "github.com/dir01/mediary/service"
	"github.com/gojuno/minimock/v3"
)

// StorageMock implements mm_service.Storage
type StorageMock struct {
	t          minimock.Tester
	finishOnce sync.Once

	funcGetJob          func(ctx context.Context, id string) (jp1 *mm_service.Job, err error)
	funcGetJobOrigin    string
	inspectFuncGetJob   func(ctx context.Context, id string)
	afterGetJobCounter  uint64
	beforeGetJobCounter uint64
	GetJobMock          mStorageMockGetJob

	funcGetMetadata          func(ctx context.Context, url string) (mp1 *mm_service.Metadata, err error)
	funcGetMetadataOrigin    string
	inspectFuncGetMetadata   func(ctx context.Context, url string)
	afterGetMetadataCounter  uint64
	beforeGetMetadataCounter uint64
	GetMetadataMock          mStorageMockGetMetadata

	funcSaveJob          func(ctx context.Context, job *mm_service.Job) (err error)
	funcSaveJobOrigin    string
	inspectFuncSaveJob   func(ctx context.Context, job *mm_service.Job)
	afterSaveJobCounter  uint64
	beforeSaveJobCounter uint64
	SaveJobMock          mStorageMockSaveJob

	funcSaveMetadata          func(ctx context.Context, metadata *mm_service.Metadata) (err error)
	funcSaveMetadataOrigin    string
	inspectFuncSaveMetadata   func(ctx context.Context, metadata *mm_service.Metadata)
	afterSaveMetadataCounter  uint64
	beforeSaveMetadataCounter uint64
	SaveMetadataMock          mStorageMockSaveMetadata
}

// NewStorageMock returns a mock for mm_service.Storage
func NewStorageMock(t minimock.Tester) *StorageMock {
	m := &StorageMock{t: t}

	if controller, ok := t.(minimock.MockController); ok {
		controller.RegisterMocker(m)
	}

	m.GetJobMock = mStorageMockGetJob{mock: m}
	m.GetJobMock.callArgs = []*StorageMockGetJobParams{}

	m.GetMetadataMock = mStorageMockGetMetadata{mock: m}
	m.GetMetadataMock.callArgs = []*StorageMockGetMetadataParams{}

	m.SaveJobMock = mStorageMockSaveJob{mock: m}
	m.SaveJobMock.callArgs = []*StorageMockSaveJobParams{}

	m.SaveMetadataMock = mStorageMockSaveMetadata{mock: m}
	m.SaveMetadataMock.callArgs = []*StorageMockSaveMetadataParams{}

	t.Cleanup(m.MinimockFinish)

	return m
}

type mStorageMockGetJob struct {
	optional           bool
	mock               *StorageMock
	defaultExpectation *StorageMockGetJobExpectation
	expectations       []*StorageMockGetJobExpectation

	callArgs []*StorageMockGetJobParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// StorageMockGetJobExpectation specifies expectation struct of the Storage.GetJob
type StorageMockGetJobExpectation struct {
	mock               *StorageMock
	params             *StorageMockGetJobParams
	paramPtrs          *StorageMockGetJobParamPtrs
	expectationOrigins StorageMockGetJobExpectationOrigins
	results            *StorageMockGetJobResults
	returnOrigin       string
	Counter            uint64
}

// StorageMockGetJobParams contains parameters of the Storage.GetJob
type StorageMockGetJobParams struct {
	ctx context.Context
	id  string
}

// StorageMockGetJobParamPtrs contains pointers to parameters of the Storage.GetJob
type StorageMockGetJobParamPtrs struct {
	ctx *context.Context
	id  *string
}

// StorageMockGetJobResults contains results of the Storage.GetJob
type StorageMockGetJobResults struct {
	jp1 *mm_service.Job
	err error
}

// StorageMockGetJobOrigins contains origins of expectations of the Storage.GetJob
type StorageMockGetJobExpectationOrigins struct {
	origin    string
	originCtx string
	originId  string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmGetJob *mStorageMockGetJob) Optional() *mStorageMockGetJob {
	mmGetJob.optional = true
	return mmGetJob
}

// Expect sets up expected params for Storage.GetJob
func (mmGetJob *mStorageMockGetJob) Expect(ctx context.Context, id string) *mStorageMockGetJob {
	if mmGetJob.mock.funcGetJob != nil {
		mmGetJob.mock.t.Fatalf("StorageMock.GetJob mock is already set by Set")
	}

	if mmGetJob.defaultExpectation == nil {
		mmGetJob.defaultExpectation = &StorageMockGetJobExpectation{}
	}

	if mmGetJob.defaultExpectation.paramPtrs != nil {
		mmGetJob.mock.t.Fatalf("StorageMock.GetJob mock is already set by ExpectParams functions")
	}

	mmGetJob.defaultExpectation.params = &StorageMockGetJobParams{ctx, id}
	mmGetJob.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmGetJob.expectations {
		if minimock.Equal(e.params, mmGetJob.defaultExpectation.params) {
			mmGetJob.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmGetJob.defaultExpectation.params)
		}
	}

	return mmGetJob
}

// ExpectCtxParam1 sets up expected param ctx for Storage.GetJob
func (mmGetJob *mStorageMockGetJob) ExpectCtxParam1(ctx context.Context) *mStorageMockGetJob {
	if mmGetJob.mock.funcGetJob != nil {
		mmGetJob.mock.t.Fatalf("StorageMock.GetJob mock is already set by Set")
	}

	if mmGetJob.defaultExpectation == nil {
		mmGetJob.defaultExpectation = &StorageMockGetJobExpectation{}
	}

	if mmGetJob.defaultExpectation.params != nil {
		mmGetJob.mock.t.Fatalf("StorageMock.GetJob mock is already set by Expect")
	}

	if mmGetJob.defaultExpectation.paramPtrs == nil {
		mmGetJob.defaultExpectation.paramPtrs = &StorageMockGetJobParamPtrs{}
	}
	mmGetJob.defaultExpectation.paramPtrs.ctx = &ctx
	mmGetJob.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmGetJob
}

// ExpectIdParam2 sets up expected param id for Storage.GetJob
func (mmGetJob *mStorageMockGetJob) ExpectIdParam2(id string) *mStorageMockGetJob {
	if mmGetJob.mock.funcGetJob != nil {
		mmGetJob.mock.t.Fatalf("StorageMock.GetJob mock is already set by Set")
	}

	if mmGetJob.defaultExpectation == nil {
		mmGetJob.defaultExpectation = &StorageMockGetJobExpectation{}
	}

	if mmGetJob.defaultExpectation.params != nil {
		mmGetJob.mock.t.Fatalf("StorageMock.GetJob mock is already set by Expect")
	}

	if mmGetJob.defaultExpectation.paramPtrs == nil {
		mmGetJob.defaultExpectation.paramPtrs = &StorageMockGetJobParamPtrs{}
	}
	mmGetJob.defaultExpectation.paramPtrs.id = &id
	mmGetJob.defaultExpectation.expectationOrigins.originId = minimock.CallerInfo(1)

	return mmGetJob
}

// Inspect accepts an inspector function that has same arguments as the Storage.GetJob
func (mmGetJob *mStorageMockGetJob) Inspect(f func(ctx context.Context, id string)) *mStorageMockGetJob {
	if mmGetJob.mock.inspectFuncGetJob != nil {
		mmGetJob.mock.t.Fatalf("Inspect function is already set for StorageMock.GetJob")
	}

	mmGetJob.mock.inspectFuncGetJob = f

	return mmGetJob
}

// Return sets up results that will be returned by Storage.GetJob
func (mmGetJob *mStorageMockGetJob) Return(jp1 *mm_service.Job, err error) *StorageMock {
	if mmGetJob.mock.funcGetJob != nil {
		mmGetJob.mock.t.Fatalf("StorageMock.GetJob mock is already set by Set")
	}

	if mmGetJob.defaultExpectation == nil {
		mmGetJob.defaultExpectation = &StorageMockGetJobExpectation{mock: mmGetJob.mock}
	}
	mmGetJob.defaultExpectation.results = &StorageMockGetJobResults{jp1, err}
	mmGetJob.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmGetJob.mock
}

// Set uses given function f to mock the Storage.GetJob method
func (mmGetJob *mStorageMockGetJob) Set(f func(ctx context.Context, id string) (jp1 *mm_service.Job, err error)) *StorageMock {
	if mmGetJob.defaultExpectation != nil {
		mmGetJob.mock.t.Fatalf("Default expectation is already set for the Storage.GetJob method")
	}

	if len(mmGetJob.expectations) > 0 {
		mmGetJob.mock.t.Fatalf("Some expectations are already set for the Storage.GetJob method")
	}

	mmGetJob.mock.funcGetJob = f
	mmGetJob.mock.funcGetJobOrigin = minimock.CallerInfo(1)
	return mmGetJob.mock
}

// When sets expectation for the Storage.GetJob which will trigger the result defined by the following
// Then helper
func (mmGetJob *mStorageMockGetJob) When(ctx context.Context, id string) *StorageMockGetJobExpectation {
	if mmGetJob.mock.funcGetJob != nil {
		mmGetJob.mock.t.Fatalf("StorageMock.GetJob mock is already set by Set")
	}

	expectation := &StorageMockGetJobExpectation{
		mock:               mmGetJob.mock,
		params:             &StorageMockGetJobParams{ctx, id},
		expectationOrigins: StorageMockGetJobExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmGetJob.expectations = append(mmGetJob.expectations, expectation)
	return expectation
}

// Then sets up Storage.GetJob return parameters for the expectation previously defined by the When method
func (e *StorageMockGetJobExpectation) Then(jp1 *mm_service.Job, err error) *StorageMock {
	e.results = &StorageMockGetJobResults{jp1, err}
	return e.mock
}

// Times sets number of times Storage.GetJob should be invoked
func (mmGetJob *mStorageMockGetJob) Times(n uint64) *mStorageMockGetJob {
	if n == 0 {
		mmGetJob.mock.t.Fatalf("Times of StorageMock.GetJob mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmGetJob.expectedInvocations, n)
	mmGetJob.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmGetJob
}

func (mmGetJob *mStorageMockGetJob) invocationsDone() bool {
	if len(mmGetJob.expectations) == 0 && mmGetJob.defaultExpectation == nil && mmGetJob.mock.funcGetJob == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmGetJob.mock.afterGetJobCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmGetJob.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// GetJob implements mm_service.Storage
func (mmGetJob *StorageMock) GetJob(ctx context.Context, id string) (jp1 *mm_service.Job, err error) {
	mm_atomic.AddUint64(&mmGetJob.beforeGetJobCounter, 1)
	defer mm_atomic.AddUint64(&mmGetJob.afterGetJobCounter, 1)

	mmGetJob.t.Helper()

	if mmGetJob.inspectFuncGetJob != nil {
		mmGetJob.inspectFuncGetJob(ctx, id)
	}

	mm_params := StorageMockGetJobParams{ctx, id}

	// Record call args
	mmGetJob.GetJobMock.mutex.Lock()
	mmGetJob.GetJobMock.callArgs = append(mmGetJob.GetJobMock.callArgs, &mm_params)
	mmGetJob.GetJobMock.mutex.Unlock()

	for _, e := range mmGetJob.GetJobMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.jp1, e.results.err
		}
	}

	if mmGetJob.GetJobMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmGetJob.GetJobMock.defaultExpectation.Counter, 1)
		mm_want := mmGetJob.GetJobMock.defaultExpectation.params
		mm_want_ptrs := mmGetJob.GetJobMock.defaultExpectation.paramPtrs

		mm_got := StorageMockGetJobParams{ctx, id}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmGetJob.t.Errorf("StorageMock.GetJob got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmGetJob.GetJobMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.id != nil && !minimock.Equal(*mm_want_ptrs.id, mm_got.id) {
				mmGetJob.t.Errorf("StorageMock.GetJob got unexpected parameter id, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmGetJob.GetJobMock.defaultExpectation.expectationOrigins.originId, *mm_want_ptrs.id, mm_got.id, minimock.Diff(*mm_want_ptrs.id, mm_got.id))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmGetJob.t.Errorf("StorageMock.GetJob got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmGetJob.GetJobMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmGetJob.GetJobMock.defaultExpectation.results
		if mm_results == nil {
			mmGetJob.t.Fatal("No results are set for the StorageMock.GetJob")
		}
		return (*mm_results).jp1, (*mm_results).err
	}
	if mmGetJob.funcGetJob != nil {
		return mmGetJob.funcGetJob(ctx, id)
	}
	mmGetJob.t.Fatalf("Unexpected call to StorageMock.GetJob. %v %v", ctx, id)
	return
}

// GetJobAfterCounter returns a count of finished StorageMock.GetJob invocations
func (mmGetJob *StorageMock) GetJobAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmGetJob.afterGetJobCounter)
}

// GetJobBeforeCounter returns a count of StorageMock.GetJob invocations
func (mmGetJob *StorageMock) GetJobBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmGetJob.beforeGetJobCounter)
}

// Calls returns a list of arguments used in each call to StorageMock.GetJob.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmGetJob *mStorageMockGetJob) Calls() []*StorageMockGetJobParams {
	mmGetJob.mutex.RLock()

	argCopy := make([]*StorageMockGetJobParams, len(mmGetJob.callArgs))
	copy(argCopy, mmGetJob.callArgs)

	mmGetJob.mutex.RUnlock()

	return argCopy
}

// MinimockGetJobDone returns true if the count of the GetJob invocations corresponds
// the number of defined expectations
func (m *StorageMock) MinimockGetJobDone() bool {
	if m.GetJobMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.GetJobMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.GetJobMock.invocationsDone()
}

// MinimockGetJobInspect logs each unmet expectation
func (m *StorageMock) MinimockGetJobInspect() {
	for _, e := range m.GetJobMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to StorageMock.GetJob at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterGetJobCounter := mm_atomic.LoadUint64(&m.afterGetJobCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.GetJobMock.defaultExpectation != nil && afterGetJobCounter < 1 {
		if m.GetJobMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to StorageMock.GetJob at\n%s", m.GetJobMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to StorageMock.GetJob at\n%s with params: %#v", m.GetJobMock.defaultExpectation.expectationOrigins.origin, *m.GetJobMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcGetJob != nil && afterGetJobCounter < 1 {
		m.t.Errorf("Expected call to StorageMock.GetJob at\n%s", m.funcGetJobOrigin)
	}

	if !m.GetJobMock.invocationsDone() && afterGetJobCounter > 0 {
		m.t.Errorf("Expected %d calls to StorageMock.GetJob at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.GetJobMock.expectedInvocations), m.GetJobMock.expectedInvocationsOrigin, afterGetJobCounter)
	}
}

type mStorageMockGetMetadata struct {
	optional           bool
	mock               *StorageMock
	defaultExpectation *StorageMockGetMetadataExpectation
	expectations       []*StorageMockGetMetadataExpectation

	callArgs []*StorageMockGetMetadataParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// StorageMockGetMetadataExpectation specifies expectation struct of the Storage.GetMetadata
type StorageMockGetMetadataExpectation struct {
	mock               *StorageMock
	params             *StorageMockGetMetadataParams
	paramPtrs          *StorageMockGetMetadataParamPtrs
	expectationOrigins StorageMockGetMetadataExpectationOrigins
	results            *StorageMockGetMetadataResults
	returnOrigin       string
	Counter            uint64
}

// StorageMockGetMetadataParams contains parameters of the Storage.GetMetadata
type StorageMockGetMetadataParams struct {
	ctx context.Context
	url string
}

// StorageMockGetMetadataParamPtrs contains pointers to parameters of the Storage.GetMetadata
type StorageMockGetMetadataParamPtrs struct {
	ctx *context.Context
	url *string
}

// StorageMockGetMetadataResults contains results of the Storage.GetMetadata
type StorageMockGetMetadataResults struct {
	mp1 *mm_service.Metadata
	err error
}

// StorageMockGetMetadataOrigins contains origins of expectations of the Storage.GetMetadata
type StorageMockGetMetadataExpectationOrigins struct {
	origin    string
	originCtx string
	originUrl string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmGetMetadata *mStorageMockGetMetadata) Optional() *mStorageMockGetMetadata {
	mmGetMetadata.optional = true
	return mmGetMetadata
}

// Expect sets up expected params for Storage.GetMetadata
func (mmGetMetadata *mStorageMockGetMetadata) Expect(ctx context.Context, url string) *mStorageMockGetMetadata {
	if mmGetMetadata.mock.funcGetMetadata != nil {
		mmGetMetadata.mock.t.Fatalf("StorageMock.GetMetadata mock is already set by Set")
	}

	if mmGetMetadata.defaultExpectation == nil {
		mmGetMetadata.defaultExpectation = &StorageMockGetMetadataExpectation{}
	}

	if mmGetMetadata.defaultExpectation.paramPtrs != nil {
		mmGetMetadata.mock.t.Fatalf("StorageMock.GetMetadata mock is already set by ExpectParams functions")
	}

	mmGetMetadata.defaultExpectation.params = &StorageMockGetMetadataParams{ctx, url}
	mmGetMetadata.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmGetMetadata.expectations {
		if minimock.Equal(e.params, mmGetMetadata.defaultExpectation.params) {
			mmGetMetadata.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmGetMetadata.defaultExpectation.params)
		}
	}

	return mmGetMetadata
}

// ExpectCtxParam1 sets up expected param ctx for Storage.GetMetadata
func (mmGetMetadata *mStorageMockGetMetadata) ExpectCtxParam1(ctx context.Context) *mStorageMockGetMetadata {
	if mmGetMetadata.mock.funcGetMetadata != nil {
		mmGetMetadata.mock.t.Fatalf("StorageMock.GetMetadata mock is already set by Set")
	}

	if mmGetMetadata.defaultExpectation == nil {
		mmGetMetadata.defaultExpectation = &StorageMockGetMetadataExpectation{}
	}

	if mmGetMetadata.defaultExpectation.params != nil {
		mmGetMetadata.mock.t.Fatalf("StorageMock.GetMetadata mock is already set by Expect")
	}

	if mmGetMetadata.defaultExpectation.paramPtrs == nil {
		mmGetMetadata.defaultExpectation.paramPtrs = &StorageMockGetMetadataParamPtrs{}
	}
	mmGetMetadata.defaultExpectation.paramPtrs.ctx = &ctx
	mmGetMetadata.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmGetMetadata
}

// ExpectUrlParam2 sets up expected param url for Storage.GetMetadata
func (mmGetMetadata *mStorageMockGetMetadata) ExpectUrlParam2(url string) *mStorageMockGetMetadata {
	if mmGetMetadata.mock.funcGetMetadata != nil {
		mmGetMetadata.mock.t.Fatalf("StorageMock.GetMetadata mock is already set by Set")
	}

	if mmGetMetadata.defaultExpectation == nil {
		mmGetMetadata.defaultExpectation = &StorageMockGetMetadataExpectation{}
	}

	if mmGetMetadata.defaultExpectation.params != nil {
		mmGetMetadata.mock.t.Fatalf("StorageMock.GetMetadata mock is already set by Expect")
	}

	if mmGetMetadata.defaultExpectation.paramPtrs == nil {
		mmGetMetadata.defaultExpectation.paramPtrs = &StorageMockGetMetadataParamPtrs{}
	}
	mmGetMetadata.defaultExpectation.paramPtrs.url = &url
	mmGetMetadata.defaultExpectation.expectationOrigins.originUrl = minimock.CallerInfo(1)

	return mmGetMetadata
}

// Inspect accepts an inspector function that has same arguments as the Storage.GetMetadata
func (mmGetMetadata *mStorageMockGetMetadata) Inspect(f func(ctx context.Context, url string)) *mStorageMockGetMetadata {
	if mmGetMetadata.mock.inspectFuncGetMetadata != nil {
		mmGetMetadata.mock.t.Fatalf("Inspect function is already set for StorageMock.GetMetadata")
	}

	mmGetMetadata.mock.inspectFuncGetMetadata = f

	return mmGetMetadata
}

// Return sets up results that will be returned by Storage.GetMetadata
func (mmGetMetadata *mStorageMockGetMetadata) Return(mp1 *mm_service.Metadata, err error) *StorageMock {
	if mmGetMetadata.mock.funcGetMetadata != nil {
		mmGetMetadata.mock.t.Fatalf("StorageMock.GetMetadata mock is already set by Set")
	}

	if mmGetMetadata.defaultExpectation == nil {
		mmGetMetadata.defaultExpectation = &StorageMockGetMetadataExpectation{mock: mmGetMetadata.mock}
	}
	mmGetMetadata.defaultExpectation.results = &StorageMockGetMetadataResults{mp1, err}
	mmGetMetadata.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmGetMetadata.mock
}

// Set uses given function f to mock the Storage.GetMetadata method
func (mmGetMetadata *mStorageMockGetMetadata) Set(f func(ctx context.Context, url string) (mp1 *mm_service.Metadata, err error)) *StorageMock {
	if mmGetMetadata.defaultExpectation != nil {
		mmGetMetadata.mock.t.Fatalf("Default expectation is already set for the Storage.GetMetadata method")
	}

	if len(mmGetMetadata.expectations) > 0 {
		mmGetMetadata.mock.t.Fatalf("Some expectations are already set for the Storage.GetMetadata method")
	}

	mmGetMetadata.mock.funcGetMetadata = f
	mmGetMetadata.mock.funcGetMetadataOrigin = minimock.CallerInfo(1)
	return mmGetMetadata.mock
}

// When sets expectation for the Storage.GetMetadata which will trigger the result defined by the following
// Then helper
func (mmGetMetadata *mStorageMockGetMetadata) When(ctx context.Context, url string) *StorageMockGetMetadataExpectation {
	if mmGetMetadata.mock.funcGetMetadata != nil {
		mmGetMetadata.mock.t.Fatalf("StorageMock.GetMetadata mock is already set by Set")
	}

	expectation := &StorageMockGetMetadataExpectation{
		mock:               mmGetMetadata.mock,
		params:             &StorageMockGetMetadataParams{ctx, url},
		expectationOrigins: StorageMockGetMetadataExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmGetMetadata.expectations = append(mmGetMetadata.expectations, expectation)
	return expectation
}

// Then sets up Storage.GetMetadata return parameters for the expectation previously defined by the When method
func (e *StorageMockGetMetadataExpectation) Then(mp1 *mm_service.Metadata, err error) *StorageMock {
	e.results = &StorageMockGetMetadataResults{mp1, err}
	return e.mock
}

// Times sets number of times Storage.GetMetadata should be invoked
func (mmGetMetadata *mStorageMockGetMetadata) Times(n uint64) *mStorageMockGetMetadata {
	if n == 0 {
		mmGetMetadata.mock.t.Fatalf("Times of StorageMock.GetMetadata mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmGetMetadata.expectedInvocations, n)
	mmGetMetadata.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmGetMetadata
}

func (mmGetMetadata *mStorageMockGetMetadata) invocationsDone() bool {
	if len(mmGetMetadata.expectations) == 0 && mmGetMetadata.defaultExpectation == nil && mmGetMetadata.mock.funcGetMetadata == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmGetMetadata.mock.afterGetMetadataCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmGetMetadata.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// GetMetadata implements mm_service.Storage
func (mmGetMetadata *StorageMock) GetMetadata(ctx context.Context, url string) (mp1 *mm_service.Metadata, err error) {
	mm_atomic.AddUint64(&mmGetMetadata.beforeGetMetadataCounter, 1)
	defer mm_atomic.AddUint64(&mmGetMetadata.afterGetMetadataCounter, 1)

	mmGetMetadata.t.Helper()

	if mmGetMetadata.inspectFuncGetMetadata != nil {
		mmGetMetadata.inspectFuncGetMetadata(ctx, url)
	}

	mm_params := StorageMockGetMetadataParams{ctx, url}

	// Record call args
	mmGetMetadata.GetMetadataMock.mutex.Lock()
	mmGetMetadata.GetMetadataMock.callArgs = append(mmGetMetadata.GetMetadataMock.callArgs, &mm_params)
	mmGetMetadata.GetMetadataMock.mutex.Unlock()

	for _, e := range mmGetMetadata.GetMetadataMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.mp1, e.results.err
		}
	}

	if mmGetMetadata.GetMetadataMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmGetMetadata.GetMetadataMock.defaultExpectation.Counter, 1)
		mm_want := mmGetMetadata.GetMetadataMock.defaultExpectation.params
		mm_want_ptrs := mmGetMetadata.GetMetadataMock.defaultExpectation.paramPtrs

		mm_got := StorageMockGetMetadataParams{ctx, url}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmGetMetadata.t.Errorf("StorageMock.GetMetadata got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmGetMetadata.GetMetadataMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.url != nil && !minimock.Equal(*mm_want_ptrs.url, mm_got.url) {
				mmGetMetadata.t.Errorf("StorageMock.GetMetadata got unexpected parameter url, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmGetMetadata.GetMetadataMock.defaultExpectation.expectationOrigins.originUrl, *mm_want_ptrs.url, mm_got.url, minimock.Diff(*mm_want_ptrs.url, mm_got.url))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmGetMetadata.t.Errorf("StorageMock.GetMetadata got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmGetMetadata.GetMetadataMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmGetMetadata.GetMetadataMock.defaultExpectation.results
		if mm_results == nil {
			mmGetMetadata.t.Fatal("No results are set for the StorageMock.GetMetadata")
		}
		return (*mm_results).mp1, (*mm_results).err
	}
	if mmGetMetadata.funcGetMetadata != nil {
		return mmGetMetadata.funcGetMetadata(ctx, url)
	}
	mmGetMetadata.t.Fatalf("Unexpected call to StorageMock.GetMetadata. %v %v", ctx, url)
	return
}

// GetMetadataAfterCounter returns a count of finished StorageMock.GetMetadata invocations
func (mmGetMetadata *StorageMock) GetMetadataAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmGetMetadata.afterGetMetadataCounter)
}

// GetMetadataBeforeCounter returns a count of StorageMock.GetMetadata invocations
func (mmGetMetadata *StorageMock) GetMetadataBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmGetMetadata.beforeGetMetadataCounter)
}

// Calls returns a list of arguments used in each call to StorageMock.GetMetadata.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmGetMetadata *mStorageMockGetMetadata) Calls() []*StorageMockGetMetadataParams {
	mmGetMetadata.mutex.RLock()

	argCopy := make([]*StorageMockGetMetadataParams, len(mmGetMetadata.callArgs))
	copy(argCopy, mmGetMetadata.callArgs)

	mmGetMetadata.mutex.RUnlock()

	return argCopy
}

// MinimockGetMetadataDone returns true if the count of the GetMetadata invocations corresponds
// the number of defined expectations
func (m *StorageMock) MinimockGetMetadataDone() bool {
	if m.GetMetadataMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.GetMetadataMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.GetMetadataMock.invocationsDone()
}

// MinimockGetMetadataInspect logs each unmet expectation
func (m *StorageMock) MinimockGetMetadataInspect() {
	for _, e := range m.GetMetadataMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to StorageMock.GetMetadata at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterGetMetadataCounter := mm_atomic.LoadUint64(&m.afterGetMetadataCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.GetMetadataMock.defaultExpectation != nil && afterGetMetadataCounter < 1 {
		if m.GetMetadataMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to StorageMock.GetMetadata at\n%s", m.GetMetadataMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to StorageMock.GetMetadata at\n%s with params: %#v", m.GetMetadataMock.defaultExpectation.expectationOrigins.origin, *m.GetMetadataMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcGetMetadata != nil && afterGetMetadataCounter < 1 {
		m.t.Errorf("Expected call to StorageMock.GetMetadata at\n%s", m.funcGetMetadataOrigin)
	}

	if !m.GetMetadataMock.invocationsDone() && afterGetMetadataCounter > 0 {
		m.t.Errorf("Expected %d calls to StorageMock.GetMetadata at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.GetMetadataMock.expectedInvocations), m.GetMetadataMock.expectedInvocationsOrigin, afterGetMetadataCounter)
	}
}

type mStorageMockSaveJob struct {
	optional           bool
	mock               *StorageMock
	defaultExpectation *StorageMockSaveJobExpectation
	expectations       []*StorageMockSaveJobExpectation

	callArgs []*StorageMockSaveJobParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// StorageMockSaveJobExpectation specifies expectation struct of the Storage.SaveJob
type StorageMockSaveJobExpectation struct {
	mock               *StorageMock
	params             *StorageMockSaveJobParams
	paramPtrs          *StorageMockSaveJobParamPtrs
	expectationOrigins StorageMockSaveJobExpectationOrigins
	results            *StorageMockSaveJobResults
	returnOrigin       string
	Counter            uint64
}

// StorageMockSaveJobParams contains parameters of the Storage.SaveJob
type StorageMockSaveJobParams struct {
	ctx context.Context
	job *mm_service.Job
}

// StorageMockSaveJobParamPtrs contains pointers to parameters of the Storage.SaveJob
type StorageMockSaveJobParamPtrs struct {
	ctx *context.Context
	job **mm_service.Job
}

// StorageMockSaveJobResults contains results of the Storage.SaveJob
type StorageMockSaveJobResults struct {
	err error
}

// StorageMockSaveJobOrigins contains origins of expectations of the Storage.SaveJob
type StorageMockSaveJobExpectationOrigins struct {
	origin    string
	originCtx string
	originJob string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmSaveJob *mStorageMockSaveJob) Optional() *mStorageMockSaveJob {
	mmSaveJob.optional = true
	return mmSaveJob
}

// Expect sets up expected params for Storage.SaveJob
func (mmSaveJob *mStorageMockSaveJob) Expect(ctx context.Context, job *mm_service.Job) *mStorageMockSaveJob {
	if mmSaveJob.mock.funcSaveJob != nil {
		mmSaveJob.mock.t.Fatalf("StorageMock.SaveJob mock is already set by Set")
	}

	if mmSaveJob.defaultExpectation == nil {
		mmSaveJob.defaultExpectation = &StorageMockSaveJobExpectation{}
	}

	if mmSaveJob.defaultExpectation.paramPtrs != nil {
		mmSaveJob.mock.t.Fatalf("StorageMock.SaveJob mock is already set by ExpectParams functions")
	}

	mmSaveJob.defaultExpectation.params = &StorageMockSaveJobParams{ctx, job}
	mmSaveJob.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmSaveJob.expectations {
		if minimock.Equal(e.params, mmSaveJob.defaultExpectation.params) {
			mmSaveJob.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmSaveJob.defaultExpectation.params)
		}
	}

	return mmSaveJob
}

// ExpectCtxParam1 sets up expected param ctx for Storage.SaveJob
func (mmSaveJob *mStorageMockSaveJob) ExpectCtxParam1(ctx context.Context) *mStorageMockSaveJob {
	if mmSaveJob.mock.funcSaveJob != nil {
		mmSaveJob.mock.t.Fatalf("StorageMock.SaveJob mock is already set by Set")
	}

	if mmSaveJob.defaultExpectation == nil {
		mmSaveJob.defaultExpectation = &StorageMockSaveJobExpectation{}
	}

	if mmSaveJob.defaultExpectation.params != nil {
		mmSaveJob.mock.t.Fatalf("StorageMock.SaveJob mock is already set by Expect")
	}

	if mmSaveJob.defaultExpectation.paramPtrs == nil {
		mmSaveJob.defaultExpectation.paramPtrs = &StorageMockSaveJobParamPtrs{}
	}
	mmSaveJob.defaultExpectation.paramPtrs.ctx = &ctx
	mmSaveJob.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmSaveJob
}

// ExpectJobParam2 sets up expected param job for Storage.SaveJob
func (mmSaveJob *mStorageMockSaveJob) ExpectJobParam2(job *mm_service.Job) *mStorageMockSaveJob {
	if mmSaveJob.mock.funcSaveJob != nil {
		mmSaveJob.mock.t.Fatalf("StorageMock.SaveJob mock is already set by Set")
	}

	if mmSaveJob.defaultExpectation == nil {
		mmSaveJob.defaultExpectation = &StorageMockSaveJobExpectation{}
	}

	if mmSaveJob.defaultExpectation.params != nil {
		mmSaveJob.mock.t.Fatalf("StorageMock.SaveJob mock is already set by Expect")
	}

	if mmSaveJob.defaultExpectation.paramPtrs == nil {
		mmSaveJob.defaultExpectation.paramPtrs = &StorageMockSaveJobParamPtrs{}
	}
	mmSaveJob.defaultExpectation.paramPtrs.job = &job
	mmSaveJob.defaultExpectation.expectationOrigins.originJob = minimock.CallerInfo(1)

	return mmSaveJob
}

// Inspect accepts an inspector function that has same arguments as the Storage.SaveJob
func (mmSaveJob *mStorageMockSaveJob) Inspect(f func(ctx context.Context, job *mm_service.Job)) *mStorageMockSaveJob {
	if mmSaveJob.mock.inspectFuncSaveJob != nil {
		mmSaveJob.mock.t.Fatalf("Inspect function is already set for StorageMock.SaveJob")
	}

	mmSaveJob.mock.inspectFuncSaveJob = f

	return mmSaveJob
}

// Return sets up results that will be returned by Storage.SaveJob
func (mmSaveJob *mStorageMockSaveJob) Return(err error) *StorageMock {
	if mmSaveJob.mock.funcSaveJob != nil {
		mmSaveJob.mock.t.Fatalf("StorageMock.SaveJob mock is already set by Set")
	}

	if mmSaveJob.defaultExpectation == nil {
		mmSaveJob.defaultExpectation = &StorageMockSaveJobExpectation{mock: mmSaveJob.mock}
	}
	mmSaveJob.defaultExpectation.results = &StorageMockSaveJobResults{err}
	mmSaveJob.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmSaveJob.mock
}

// Set uses given function f to mock the Storage.SaveJob method
func (mmSaveJob *mStorageMockSaveJob) Set(f func(ctx context.Context, job *mm_service.Job) (err error)) *StorageMock {
	if mmSaveJob.defaultExpectation != nil {
		mmSaveJob.mock.t.Fatalf("Default expectation is already set for the Storage.SaveJob method")
	}

	if len(mmSaveJob.expectations) > 0 {
		mmSaveJob.mock.t.Fatalf("Some expectations are already set for the Storage.SaveJob method")
	}

	mmSaveJob.mock.funcSaveJob = f
	mmSaveJob.mock.funcSaveJobOrigin = minimock.CallerInfo(1)
	return mmSaveJob.mock
}

// When sets expectation for the Storage.SaveJob which will trigger the result defined by the following
// Then helper
func (mmSaveJob *mStorageMockSaveJob) When(ctx context.Context, job *mm_service.Job) *StorageMockSaveJobExpectation {
	if mmSaveJob.mock.funcSaveJob != nil {
		mmSaveJob.mock.t.Fatalf("StorageMock.SaveJob mock is already set by Set")
	}

	expectation := &StorageMockSaveJobExpectation{
		mock:               mmSaveJob.mock,
		params:             &StorageMockSaveJobParams{ctx, job},
		expectationOrigins: StorageMockSaveJobExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmSaveJob.expectations = append(mmSaveJob.expectations, expectation)
	return expectation
}

// Then sets up Storage.SaveJob return parameters for the expectation previously defined by the When method
func (e *StorageMockSaveJobExpectation) Then(err error) *StorageMock {
	e.results = &StorageMockSaveJobResults{err}
	return e.mock
}

// Times sets number of times Storage.SaveJob should be invoked
func (mmSaveJob *mStorageMockSaveJob) Times(n uint64) *mStorageMockSaveJob {
	if n == 0 {
		mmSaveJob.mock.t.Fatalf("Times of StorageMock.SaveJob mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmSaveJob.expectedInvocations, n)
	mmSaveJob.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmSaveJob
}

func (mmSaveJob *mStorageMockSaveJob) invocationsDone() bool {
	if len(mmSaveJob.expectations) == 0 && mmSaveJob.defaultExpectation == nil && mmSaveJob.mock.funcSaveJob == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmSaveJob.mock.afterSaveJobCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmSaveJob.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// SaveJob implements mm_service.Storage
func (mmSaveJob *StorageMock) SaveJob(ctx context.Context, job *mm_service.Job) (err error) {
	mm_atomic.AddUint64(&mmSaveJob.beforeSaveJobCounter, 1)
	defer mm_atomic.AddUint64(&mmSaveJob.afterSaveJobCounter, 1)

	mmSaveJob.t.Helper()

	if mmSaveJob.inspectFuncSaveJob != nil {
		mmSaveJob.inspectFuncSaveJob(ctx, job)
	}

	mm_params := StorageMockSaveJobParams{ctx, job}

	// Record call args
	mmSaveJob.SaveJobMock.mutex.Lock()
	mmSaveJob.SaveJobMock.callArgs = append(mmSaveJob.SaveJobMock.callArgs, &mm_params)
	mmSaveJob.SaveJobMock.mutex.Unlock()

	for _, e := range mmSaveJob.SaveJobMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.err
		}
	}

	if mmSaveJob.SaveJobMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmSaveJob.SaveJobMock.defaultExpectation.Counter, 1)
		mm_want := mmSaveJob.SaveJobMock.defaultExpectation.params
		mm_want_ptrs := mmSaveJob.SaveJobMock.defaultExpectation.paramPtrs

		mm_got := StorageMockSaveJobParams{ctx, job}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmSaveJob.t.Errorf("StorageMock.SaveJob got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmSaveJob.SaveJobMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.job != nil && !minimock.Equal(*mm_want_ptrs.job, mm_got.job) {
				mmSaveJob.t.Errorf("StorageMock.SaveJob got unexpected parameter job, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmSaveJob.SaveJobMock.defaultExpectation.expectationOrigins.originJob, *mm_want_ptrs.job, mm_got.job, minimock.Diff(*mm_want_ptrs.job, mm_got.job))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmSaveJob.t.Errorf("StorageMock.SaveJob got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmSaveJob.SaveJobMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmSaveJob.SaveJobMock.defaultExpectation.results
		if mm_results == nil {
			mmSaveJob.t.Fatal("No results are set for the StorageMock.SaveJob")
		}
		return (*mm_results).err
	}
	if mmSaveJob.funcSaveJob != nil {
		return mmSaveJob.funcSaveJob(ctx, job)
	}
	mmSaveJob.t.Fatalf("Unexpected call to StorageMock.SaveJob. %v %v", ctx, job)
	return
}

// SaveJobAfterCounter returns a count of finished StorageMock.SaveJob invocations
func (mmSaveJob *StorageMock) SaveJobAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmSaveJob.afterSaveJobCounter)
}

// SaveJobBeforeCounter returns a count of StorageMock.SaveJob invocations
func (mmSaveJob *StorageMock) SaveJobBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmSaveJob.beforeSaveJobCounter)
}

// Calls returns a list of arguments used in each call to StorageMock.SaveJob.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmSaveJob *mStorageMockSaveJob) Calls() []*StorageMockSaveJobParams {
	mmSaveJob.mutex.RLock()

	argCopy := make([]*StorageMockSaveJobParams, len(mmSaveJob.callArgs))
	copy(argCopy, mmSaveJob.callArgs)

	mmSaveJob.mutex.RUnlock()

	return argCopy
}

// MinimockSaveJobDone returns true if the count of the SaveJob invocations corresponds
// the number of defined expectations
func (m *StorageMock) MinimockSaveJobDone() bool {
	if m.SaveJobMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.SaveJobMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.SaveJobMock.invocationsDone()
}

// MinimockSaveJobInspect logs each unmet expectation
func (m *StorageMock) MinimockSaveJobInspect() {
	for _, e := range m.SaveJobMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to StorageMock.SaveJob at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterSaveJobCounter := mm_atomic.LoadUint64(&m.afterSaveJobCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.SaveJobMock.defaultExpectation != nil && afterSaveJobCounter < 1 {
		if m.SaveJobMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to StorageMock.SaveJob at\n%s", m.SaveJobMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to StorageMock.SaveJob at\n%s with params: %#v", m.SaveJobMock.defaultExpectation.expectationOrigins.origin, *m.SaveJobMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcSaveJob != nil && afterSaveJobCounter < 1 {
		m.t.Errorf("Expected call to StorageMock.SaveJob at\n%s", m.funcSaveJobOrigin)
	}

	if !m.SaveJobMock.invocationsDone() && afterSaveJobCounter > 0 {
		m.t.Errorf("Expected %d calls to StorageMock.SaveJob at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.SaveJobMock.expectedInvocations), m.SaveJobMock.expectedInvocationsOrigin, afterSaveJobCounter)
	}
}

type mStorageMockSaveMetadata struct {
	optional           bool
	mock               *StorageMock
	defaultExpectation *StorageMockSaveMetadataExpectation
	expectations       []*StorageMockSaveMetadataExpectation

	callArgs []*StorageMockSaveMetadataParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// StorageMockSaveMetadataExpectation specifies expectation struct of the Storage.SaveMetadata
type StorageMockSaveMetadataExpectation struct {
	mock               *StorageMock
	params             *StorageMockSaveMetadataParams
	paramPtrs          *StorageMockSaveMetadataParamPtrs
	expectationOrigins StorageMockSaveMetadataExpectationOrigins
	results            *StorageMockSaveMetadataResults
	returnOrigin       string
	Counter            uint64
}

// StorageMockSaveMetadataParams contains parameters of the Storage.SaveMetadata
type StorageMockSaveMetadataParams struct {
	ctx      context.Context
	metadata *mm_service.Metadata
}

// StorageMockSaveMetadataParamPtrs contains pointers to parameters of the Storage.SaveMetadata
type StorageMockSaveMetadataParamPtrs struct {
	ctx      *context.Context
	metadata **mm_service.Metadata
}

// StorageMockSaveMetadataResults contains results of the Storage.SaveMetadata
type StorageMockSaveMetadataResults struct {
	err error
}

// StorageMockSaveMetadataOrigins contains origins of expectations of the Storage.SaveMetadata
type StorageMockSaveMetadataExpectationOrigins struct {
	origin         string
	originCtx      string
	originMetadata string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmSaveMetadata *mStorageMockSaveMetadata) Optional() *mStorageMockSaveMetadata {
	mmSaveMetadata.optional = true
	return mmSaveMetadata
}

// Expect sets up expected params for Storage.SaveMetadata
func (mmSaveMetadata *mStorageMockSaveMetadata) Expect(ctx context.Context, metadata *mm_service.Metadata) *mStorageMockSaveMetadata {
	if mmSaveMetadata.mock.funcSaveMetadata != nil {
		mmSaveMetadata.mock.t.Fatalf("StorageMock.SaveMetadata mock is already set by Set")
	}

	if mmSaveMetadata.defaultExpectation == nil {
		mmSaveMetadata.defaultExpectation = &StorageMockSaveMetadataExpectation{}
	}

	if mmSaveMetadata.defaultExpectation.paramPtrs != nil {
		mmSaveMetadata.mock.t.Fatalf("StorageMock.SaveMetadata mock is already set by ExpectParams functions")
	}

	mmSaveMetadata.defaultExpectation.params = &StorageMockSaveMetadataParams{ctx, metadata}
	mmSaveMetadata.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmSaveMetadata.expectations {
		if minimock.Equal(e.params, mmSaveMetadata.defaultExpectation.params) {
			mmSaveMetadata.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmSaveMetadata.defaultExpectation.params)
		}
	}

	return mmSaveMetadata
}

// ExpectCtxParam1 sets up expected param ctx for Storage.SaveMetadata
func (mmSaveMetadata *mStorageMockSaveMetadata) ExpectCtxParam1(ctx context.Context) *mStorageMockSaveMetadata {
	if mmSaveMetadata.mock.funcSaveMetadata != nil {
		mmSaveMetadata.mock.t.Fatalf("StorageMock.SaveMetadata mock is already set by Set")
	}

	if mmSaveMetadata.defaultExpectation == nil {
		mmSaveMetadata.defaultExpectation = &StorageMockSaveMetadataExpectation{}
	}

	if mmSaveMetadata.defaultExpectation.params != nil {
		mmSaveMetadata.mock.t.Fatalf("StorageMock.SaveMetadata mock is already set by Expect")
	}

	if mmSaveMetadata.defaultExpectation.paramPtrs == nil {
		mmSaveMetadata.defaultExpectation.paramPtrs = &StorageMockSaveMetadataParamPtrs{}
	}
	mmSaveMetadata.defaultExpectation.paramPtrs.ctx = &ctx
	mmSaveMetadata.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmSaveMetadata
}

// ExpectMetadataParam2 sets up expected param metadata for Storage.SaveMetadata
func (mmSaveMetadata *mStorageMockSaveMetadata) ExpectMetadataParam2(metadata *mm_service.Metadata) *mStorageMockSaveMetadata {
	if mmSaveMetadata.mock.funcSaveMetadata != nil {
		mmSaveMetadata.mock.t.Fatalf("StorageMock.SaveMetadata mock is already set by Set")
	}

	if mmSaveMetadata.defaultExpectation == nil {
		mmSaveMetadata.defaultExpectation = &StorageMockSaveMetadataExpectation{}
	}

	if mmSaveMetadata.defaultExpectation.params != nil {
		mmSaveMetadata.mock.t.Fatalf("StorageMock.SaveMetadata mock is already set by Expect")
	}

	if mmSaveMetadata.defaultExpectation.paramPtrs == nil {
		mmSaveMetadata.defaultExpectation.paramPtrs = &StorageMockSaveMetadataParamPtrs{}
	}
	mmSaveMetadata.defaultExpectation.paramPtrs.metadata = &metadata
	mmSaveMetadata.defaultExpectation.expectationOrigins.originMetadata = minimock.CallerInfo(1)

	return mmSaveMetadata
}

// Inspect accepts an inspector function that has same arguments as the Storage.SaveMetadata
func (mmSaveMetadata *mStorageMockSaveMetadata) Inspect(f func(ctx context.Context, metadata *mm_service.Metadata)) *mStorageMockSaveMetadata {
	if mmSaveMetadata.mock.inspectFuncSaveMetadata != nil {
		mmSaveMetadata.mock.t.Fatalf("Inspect function is already set for StorageMock.SaveMetadata")
	}

	mmSaveMetadata.mock.inspectFuncSaveMetadata = f

	return mmSaveMetadata
}

// Return sets up results that will be returned by Storage.SaveMetadata
func (mmSaveMetadata *mStorageMockSaveMetadata) Return(err error) *StorageMock {
	if mmSaveMetadata.mock.funcSaveMetadata != nil {
		mmSaveMetadata.mock.t.Fatalf("StorageMock.SaveMetadata mock is already set by Set")
	}

	if mmSaveMetadata.defaultExpectation == nil {
		mmSaveMetadata.defaultExpectation = &StorageMockSaveMetadataExpectation{mock: mmSaveMetadata.mock}
	}
	mmSaveMetadata.defaultExpectation.results = &StorageMockSaveMetadataResults{err}
	mmSaveMetadata.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmSaveMetadata.mock
}

// Set uses given function f to mock the Storage.SaveMetadata method
func (mmSaveMetadata *mStorageMockSaveMetadata) Set(f func(ctx context.Context, metadata *mm_service.Metadata) (err error)) *StorageMock {
	if mmSaveMetadata.defaultExpectation != nil {
		mmSaveMetadata.mock.t.Fatalf("Default expectation is already set for the Storage.SaveMetadata method")
	}

	if len(mmSaveMetadata.expectations) > 0 {
		mmSaveMetadata.mock.t.Fatalf("Some expectations are already set for the Storage.SaveMetadata method")
	}

	mmSaveMetadata.mock.funcSaveMetadata = f
	mmSaveMetadata.mock.funcSaveMetadataOrigin = minimock.CallerInfo(1)
	return mmSaveMetadata.mock
}

// When sets expectation for the Storage.SaveMetadata which will trigger the result defined by the following
// Then helper
func (mmSaveMetadata *mStorageMockSaveMetadata) When(ctx context.Context, metadata *mm_service.Metadata) *StorageMockSaveMetadataExpectation {
	if mmSaveMetadata.mock.funcSaveMetadata != nil {
		mmSaveMetadata.mock.t.Fatalf("StorageMock.SaveMetadata mock is already set by Set")
	}

	expectation := &StorageMockSaveMetadataExpectation{
		mock:               mmSaveMetadata.mock,
		params:             &StorageMockSaveMetadataParams{ctx, metadata},
		expectationOrigins: StorageMockSaveMetadataExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmSaveMetadata.expectations = append(mmSaveMetadata.expectations, expectation)
	return expectation
}

// Then sets up Storage.SaveMetadata return parameters for the expectation previously defined by the When method
func (e *StorageMockSaveMetadataExpectation) Then(err error) *StorageMock {
	e.results = &StorageMockSaveMetadataResults{err}
	return e.mock
}

// Times sets number of times Storage.SaveMetadata should be invoked
func (mmSaveMetadata *mStorageMockSaveMetadata) Times(n uint64) *mStorageMockSaveMetadata {
	if n == 0 {
		mmSaveMetadata.mock.t.Fatalf("Times of StorageMock.SaveMetadata mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmSaveMetadata.expectedInvocations, n)
	mmSaveMetadata.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmSaveMetadata
}

func (mmSaveMetadata *mStorageMockSaveMetadata) invocationsDone() bool {
	if len(mmSaveMetadata.expectations) == 0 && mmSaveMetadata.defaultExpectation == nil && mmSaveMetadata.mock.funcSaveMetadata == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmSaveMetadata.mock.afterSaveMetadataCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmSaveMetadata.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// SaveMetadata implements mm_service.Storage
func (mmSaveMetadata *StorageMock) SaveMetadata(ctx context.Context, metadata *mm_service.Metadata) (err error) {
	mm_atomic.AddUint64(&mmSaveMetadata.beforeSaveMetadataCounter, 1)
	defer mm_atomic.AddUint64(&mmSaveMetadata.afterSaveMetadataCounter, 1)

	mmSaveMetadata.t.Helper()

	if mmSaveMetadata.inspectFuncSaveMetadata != nil {
		mmSaveMetadata.inspectFuncSaveMetadata(ctx, metadata)
	}

	mm_params := StorageMockSaveMetadataParams{ctx, metadata}

	// Record call args
	mmSaveMetadata.SaveMetadataMock.mutex.Lock()
	mmSaveMetadata.SaveMetadataMock.callArgs = append(mmSaveMetadata.SaveMetadataMock.callArgs, &mm_params)
	mmSaveMetadata.SaveMetadataMock.mutex.Unlock()

	for _, e := range mmSaveMetadata.SaveMetadataMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.err
		}
	}

	if mmSaveMetadata.SaveMetadataMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmSaveMetadata.SaveMetadataMock.defaultExpectation.Counter, 1)
		mm_want := mmSaveMetadata.SaveMetadataMock.defaultExpectation.params
		mm_want_ptrs := mmSaveMetadata.SaveMetadataMock.defaultExpectation.paramPtrs

		mm_got := StorageMockSaveMetadataParams{ctx, metadata}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmSaveMetadata.t.Errorf("StorageMock.SaveMetadata got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmSaveMetadata.SaveMetadataMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.metadata != nil && !minimock.Equal(*mm_want_ptrs.metadata, mm_got.metadata) {
				mmSaveMetadata.t.Errorf("StorageMock.SaveMetadata got unexpected parameter metadata, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmSaveMetadata.SaveMetadataMock.defaultExpectation.expectationOrigins.originMetadata, *mm_want_ptrs.metadata, mm_got.metadata, minimock.Diff(*mm_want_ptrs.metadata, mm_got.metadata))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmSaveMetadata.t.Errorf("StorageMock.SaveMetadata got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmSaveMetadata.SaveMetadataMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmSaveMetadata.SaveMetadataMock.defaultExpectation.results
		if mm_results == nil {
			mmSaveMetadata.t.Fatal("No results are set for the StorageMock.SaveMetadata")
		}
		return (*mm_results).err
	}
	if mmSaveMetadata.funcSaveMetadata != nil {
		return mmSaveMetadata.funcSaveMetadata(ctx, metadata)
	}
	mmSaveMetadata.t.Fatalf("Unexpected call to StorageMock.SaveMetadata. %v %v", ctx, metadata)
	return
}

// SaveMetadataAfterCounter returns a count of finished StorageMock.SaveMetadata invocations
func (mmSaveMetadata *StorageMock) SaveMetadataAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmSaveMetadata.afterSaveMetadataCounter)
}

// SaveMetadataBeforeCounter returns a count of StorageMock.SaveMetadata invocations
func (mmSaveMetadata *StorageMock) SaveMetadataBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmSaveMetadata.beforeSaveMetadataCounter)
}

// Calls returns a list of arguments used in each call to StorageMock.SaveMetadata.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmSaveMetadata *mStorageMockSaveMetadata) Calls() []*StorageMockSaveMetadataParams {
	mmSaveMetadata.mutex.RLock()

	argCopy := make([]*StorageMockSaveMetadataParams, len(mmSaveMetadata.callArgs))
	copy(argCopy, mmSaveMetadata.callArgs)

	mmSaveMetadata.mutex.RUnlock()

	return argCopy
}

// MinimockSaveMetadataDone returns true if the count of the SaveMetadata invocations corresponds
// the number of defined expectations
func (m *StorageMock) MinimockSaveMetadataDone() bool {
	if m.SaveMetadataMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.SaveMetadataMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.SaveMetadataMock.invocationsDone()
}

// MinimockSaveMetadataInspect logs each unmet expectation
func (m *StorageMock) MinimockSaveMetadataInspect() {
	for _, e := range m.SaveMetadataMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to StorageMock.SaveMetadata at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterSaveMetadataCounter := mm_atomic.LoadUint64(&m.afterSaveMetadataCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.SaveMetadataMock.defaultExpectation != nil && afterSaveMetadataCounter < 1 {
		if m.SaveMetadataMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to StorageMock.SaveMetadata at\n%s", m.SaveMetadataMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to StorageMock.SaveMetadata at\n%s with params: %#v", m.SaveMetadataMock.defaultExpectation.expectationOrigins.origin, *m.SaveMetadataMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcSaveMetadata != nil && afterSaveMetadataCounter < 1 {
		m.t.Errorf("Expected call to StorageMock.SaveMetadata at\n%s", m.funcSaveMetadataOrigin)
	}

	if !m.SaveMetadataMock.invocationsDone() && afterSaveMetadataCounter > 0 {
		m.t.Errorf("Expected %d calls to StorageMock.SaveMetadata at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.SaveMetadataMock.expectedInvocations), m.SaveMetadataMock.expectedInvocationsOrigin, afterSaveMetadataCounter)
	}
}

// MinimockFinish checks that all mocked methods have been called the expected number of times
func (m *StorageMock) MinimockFinish() {
	m.finishOnce.Do(func() {
		if !m.minimockDone() {
			m.MinimockGetJobInspect()

			m.MinimockGetMetadataInspect()

			m.MinimockSaveJobInspect()

			m.MinimockSaveMetadataInspect()
		}
	})
}

// MinimockWait waits for all mocked methods to be called the expected number of times
func (m *StorageMock) MinimockWait(timeout mm_time.Duration) {
	timeoutCh := mm_time.After(timeout)
	for {
		if m.minimockDone() {
			return
		}
		select {
		case <-timeoutCh:
			m.MinimockFinish()
			return
		case <-mm_time.After(10 * mm_time.Millisecond):
		}
	}
}

func (m *StorageMock) minimockDone() bool {
	done := true
	return done &&
		m.MinimockGetJobDone() &&
		m.MinimockGetMetadataDone() &&
		m.MinimockSaveJobDone() &&
		m.MinimockSaveMetadataDone()
}
