package mocks

// Code generated by http://github.com/gojuno/minimock (dev). DO NOT EDIT.

import (
	"context"
	"sync"
	mm_atomic "sync/atomic"
	mm_time "time"

	"github.com/gojuno/minimock/v3"
)

// UploaderMock implements service.Uploader
type UploaderMock struct {
	t minimock.Tester

	funcUpload          func(ctx context.Context, filepath string, url string) (err error)
	inspectFuncUpload   func(ctx context.Context, filepath string, url string)
	afterUploadCounter  uint64
	beforeUploadCounter uint64
	UploadMock          mUploaderMockUpload
}

// NewUploaderMock returns a mock for service.Uploader
func NewUploaderMock(t minimock.Tester) *UploaderMock {
	m := &UploaderMock{t: t}
	if controller, ok := t.(minimock.MockController); ok {
		controller.RegisterMocker(m)
	}

	m.UploadMock = mUploaderMockUpload{mock: m}
	m.UploadMock.callArgs = []*UploaderMockUploadParams{}

	return m
}

type mUploaderMockUpload struct {
	mock               *UploaderMock
	defaultExpectation *UploaderMockUploadExpectation
	expectations       []*UploaderMockUploadExpectation

	callArgs []*UploaderMockUploadParams
	mutex    sync.RWMutex
}

// UploaderMockUploadExpectation specifies expectation struct of the Uploader.Upload
type UploaderMockUploadExpectation struct {
	mock    *UploaderMock
	params  *UploaderMockUploadParams
	results *UploaderMockUploadResults
	Counter uint64
}

// UploaderMockUploadParams contains parameters of the Uploader.Upload
type UploaderMockUploadParams struct {
	ctx      context.Context
	filepath string
	url      string
}

// UploaderMockUploadResults contains results of the Uploader.Upload
type UploaderMockUploadResults struct {
	err error
}

// Expect sets up expected params for Uploader.Upload
func (mmUpload *mUploaderMockUpload) Expect(ctx context.Context, filepath string, url string) *mUploaderMockUpload {
	if mmUpload.mock.funcUpload != nil {
		mmUpload.mock.t.Fatalf("UploaderMock.Upload mock is already set by Set")
	}

	if mmUpload.defaultExpectation == nil {
		mmUpload.defaultExpectation = &UploaderMockUploadExpectation{}
	}

	mmUpload.defaultExpectation.params = &UploaderMockUploadParams{ctx, filepath, url}
	for _, e := range mmUpload.expectations {
		if minimock.Equal(e.params, mmUpload.defaultExpectation.params) {
			mmUpload.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmUpload.defaultExpectation.params)
		}
	}

	return mmUpload
}

// Inspect accepts an inspector function that has same arguments as the Uploader.Upload
func (mmUpload *mUploaderMockUpload) Inspect(f func(ctx context.Context, filepath string, url string)) *mUploaderMockUpload {
	if mmUpload.mock.inspectFuncUpload != nil {
		mmUpload.mock.t.Fatalf("Inspect function is already set for UploaderMock.Upload")
	}

	mmUpload.mock.inspectFuncUpload = f

	return mmUpload
}

// Return sets up results that will be returned by Uploader.Upload
func (mmUpload *mUploaderMockUpload) Return(err error) *UploaderMock {
	if mmUpload.mock.funcUpload != nil {
		mmUpload.mock.t.Fatalf("UploaderMock.Upload mock is already set by Set")
	}

	if mmUpload.defaultExpectation == nil {
		mmUpload.defaultExpectation = &UploaderMockUploadExpectation{mock: mmUpload.mock}
	}
	mmUpload.defaultExpectation.results = &UploaderMockUploadResults{err}
	return mmUpload.mock
}

//Set uses given function f to mock the Uploader.Upload method
func (mmUpload *mUploaderMockUpload) Set(f func(ctx context.Context, filepath string, url string) (err error)) *UploaderMock {
	if mmUpload.defaultExpectation != nil {
		mmUpload.mock.t.Fatalf("Default expectation is already set for the Uploader.Upload method")
	}

	if len(mmUpload.expectations) > 0 {
		mmUpload.mock.t.Fatalf("Some expectations are already set for the Uploader.Upload method")
	}

	mmUpload.mock.funcUpload = f
	return mmUpload.mock
}

// When sets expectation for the Uploader.Upload which will trigger the result defined by the following
// Then helper
func (mmUpload *mUploaderMockUpload) When(ctx context.Context, filepath string, url string) *UploaderMockUploadExpectation {
	if mmUpload.mock.funcUpload != nil {
		mmUpload.mock.t.Fatalf("UploaderMock.Upload mock is already set by Set")
	}

	expectation := &UploaderMockUploadExpectation{
		mock:   mmUpload.mock,
		params: &UploaderMockUploadParams{ctx, filepath, url},
	}
	mmUpload.expectations = append(mmUpload.expectations, expectation)
	return expectation
}

// Then sets up Uploader.Upload return parameters for the expectation previously defined by the When method
func (e *UploaderMockUploadExpectation) Then(err error) *UploaderMock {
	e.results = &UploaderMockUploadResults{err}
	return e.mock
}

// Upload implements service.Uploader
func (mmUpload *UploaderMock) Upload(ctx context.Context, filepath string, url string) (err error) {
	mm_atomic.AddUint64(&mmUpload.beforeUploadCounter, 1)
	defer mm_atomic.AddUint64(&mmUpload.afterUploadCounter, 1)

	if mmUpload.inspectFuncUpload != nil {
		mmUpload.inspectFuncUpload(ctx, filepath, url)
	}

	mm_params := &UploaderMockUploadParams{ctx, filepath, url}

	// Record call args
	mmUpload.UploadMock.mutex.Lock()
	mmUpload.UploadMock.callArgs = append(mmUpload.UploadMock.callArgs, mm_params)
	mmUpload.UploadMock.mutex.Unlock()

	for _, e := range mmUpload.UploadMock.expectations {
		if minimock.Equal(e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.err
		}
	}

	if mmUpload.UploadMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmUpload.UploadMock.defaultExpectation.Counter, 1)
		mm_want := mmUpload.UploadMock.defaultExpectation.params
		mm_got := UploaderMockUploadParams{ctx, filepath, url}
		if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmUpload.t.Errorf("UploaderMock.Upload got unexpected parameters, want: %#v, got: %#v%s\n", *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmUpload.UploadMock.defaultExpectation.results
		if mm_results == nil {
			mmUpload.t.Fatal("No results are set for the UploaderMock.Upload")
		}
		return (*mm_results).err
	}
	if mmUpload.funcUpload != nil {
		return mmUpload.funcUpload(ctx, filepath, url)
	}
	mmUpload.t.Fatalf("Unexpected call to UploaderMock.Upload. %v %v %v", ctx, filepath, url)
	return
}

// UploadAfterCounter returns a count of finished UploaderMock.Upload invocations
func (mmUpload *UploaderMock) UploadAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmUpload.afterUploadCounter)
}

// UploadBeforeCounter returns a count of UploaderMock.Upload invocations
func (mmUpload *UploaderMock) UploadBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmUpload.beforeUploadCounter)
}

// Calls returns a list of arguments used in each call to UploaderMock.Upload.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmUpload *mUploaderMockUpload) Calls() []*UploaderMockUploadParams {
	mmUpload.mutex.RLock()

	argCopy := make([]*UploaderMockUploadParams, len(mmUpload.callArgs))
	copy(argCopy, mmUpload.callArgs)

	mmUpload.mutex.RUnlock()

	return argCopy
}

// MinimockUploadDone returns true if the count of the Upload invocations corresponds
// the number of defined expectations
func (m *UploaderMock) MinimockUploadDone() bool {
	for _, e := range m.UploadMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	// if default expectation was set then invocations count should be greater than zero
	if m.UploadMock.defaultExpectation != nil && mm_atomic.LoadUint64(&m.afterUploadCounter) < 1 {
		return false
	}
	// if func was set then invocations count should be greater than zero
	if m.funcUpload != nil && mm_atomic.LoadUint64(&m.afterUploadCounter) < 1 {
		return false
	}
	return true
}

// MinimockUploadInspect logs each unmet expectation
func (m *UploaderMock) MinimockUploadInspect() {
	for _, e := range m.UploadMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to UploaderMock.Upload with params: %#v", *e.params)
		}
	}

	// if default expectation was set then invocations count should be greater than zero
	if m.UploadMock.defaultExpectation != nil && mm_atomic.LoadUint64(&m.afterUploadCounter) < 1 {
		if m.UploadMock.defaultExpectation.params == nil {
			m.t.Error("Expected call to UploaderMock.Upload")
		} else {
			m.t.Errorf("Expected call to UploaderMock.Upload with params: %#v", *m.UploadMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcUpload != nil && mm_atomic.LoadUint64(&m.afterUploadCounter) < 1 {
		m.t.Error("Expected call to UploaderMock.Upload")
	}
}

// MinimockFinish checks that all mocked methods have been called the expected number of times
func (m *UploaderMock) MinimockFinish() {
	if !m.minimockDone() {
		m.MinimockUploadInspect()
		m.t.FailNow()
	}
}

// MinimockWait waits for all mocked methods to be called the expected number of times
func (m *UploaderMock) MinimockWait(timeout mm_time.Duration) {
	timeoutCh := mm_time.After(timeout)
	for {
		if m.minimockDone() {
			return
		}
		select {
		case <-timeoutCh:
			m.MinimockFinish()
			return
		case <-mm_time.After(10 * mm_time.Millisecond):
		}
	}
}

func (m *UploaderMock) minimockDone() bool {
	done := true
	return done &&
		m.MinimockUploadDone()
}
